# The docker-compose.yml file describes the services that make your app. In this example those services are a web server and database.

version: "3.8"
   
services:
    django:
        build: .
        container_name: django_blog_container
        command: python mysite/manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/django_dir
        ports:
            - "8000:8000"
        depends_on:
            - db
        image: app:django
    db:
        image: mysql:5.7
        container_name: mysqldb_blog_container
        environment:
            - MYSQL_DATABASE=django-blog-app
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            # - MYSQL_USER: 'root'
            # - MYSQL_PASSWORD: 'password'
            # - MYSQL_ROOT_PASSWORD: 'password'
        volumes:
            - ./data/mysql/db:/var/lib/mysql
